language: php
sudo: false

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

env:
  global:
    - PLUGIN=Gantt
    - KANBOARD_REPO=https://github.com/kanboard/kanboard.git
  matrix:
    - DB=sqlite
    - DB=mysql
    - DB=postgres

matrix:
  fast_finish: true

install:
  - git clone --depth 1 $KANBOARD_REPO
  - ln -s $TRAVIS_BUILD_DIR kanboard/plugins/$PLUGIN

before_script:
  - cd kanboard
  - phpenv config-add tests/php.ini
  - composer install
  - ls -la plugins/

script:
  - phpunit -c tests/units.$DB.xml plugins/$PLUGIN/Test/
